### ISSUE TITLE
Timeline is always rendered broken

### ISSUE THREAD

**Issue by bitfede** [rsuite/rsuite.github.io#158]
Hello,

hope someone can help with this...

I wanted to implement a Timeline component in my UI, so I copied the code from https://rsuitejs.com/en/components/timeline and pasted it into my app, so I could modify it and adapt it to my specific needs.

The problem is that the timeline is always rendered broken, here's a picture:

<img width="422" alt="Screen Shot 2019-11-14 at 6 25 22 PM" src="https://user-images.githubusercontent.com/15684622/68880894-70b2f600-070c-11ea-9c48-ccc442054deb.png">

As you can see it's completely broken, and I have no idea how to make it work, since there's not much I can do, it should render exactly as what you show on the website docs.

Please advise. Thank you very much!

**Comment by simonguo** [comment]
The examples in the documentation contain a portion of the customization of css
```css
.custom-timeline {
  margin-left: 20px;
}

.custom-timeline .rs-timeline-item-custom-dot .rs-icon {
  border: 2px solid #ddd;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  font-size: 18px;
  padding-top: 9px;
  color: #999;
  margin-left: -13px;
}
.custom-timeline .rs-timeline-item-content {
  margin-left: 24px;
}
```
https://github.com/rsuite/rsuite.github.io/blob/master/src/pages/components/timeline/styles.less
